<div id="p-range" data-bind="scope:'p_range'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#p-range": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "p_range": {
                        "component": "CrimsonAgility_ProductsinRange/js/product-range"
                    }
                }
            }
        }
    }
    </script>
</div>